### ISSUE TITLE
[EDITION] Self-reflexive graph properties not correctly calculated?

### ISSUE THREAD

**Issue by musicEnfanthen** [webern-unibas-ch/awg-app#18]
If we have a self-reflexive property in the first triple, the corresponding graph nodes are created twice. 

```
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix awg: <https://edition.anton-webern.ch/webern-onto#> .

<A> <shouldBe> <A> .  # creates two nodes for A
<A> <shouldbe> <B> .  # if this is the first triple, only one node A is created

<A> <foaf:knows> <A> .
<A> <pc:t0> <A> .


<B> rdf:type dc:Agent .
<A> rdf:type dc:Agent .

```

![Bildschirmfoto 2020-07-13 um 11 08 42](https://user-images.githubusercontent.com/21059419/87286552-4878d280-c4f9-11ea-8fde-21a9ac239e72.png)

If this triple is not the first one, only one node A is created.

```
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix awg: <https://edition.anton-webern.ch/webern-onto#> .

<A> <shouldbe> <B> .  # switched to first position
<A> <shouldBe> <A> .  # now only one node A is created

<A> <foaf:knows> <A> .
<A> <pc:t0> <A> .


<B> rdf:type dc:Agent .
<A> rdf:type dc:Agent .

```

![Bildschirmfoto 2020-07-13 um 11 09 02](https://user-images.githubusercontent.com/21059419/87286710-7bbb6180-c4f9-11ea-8870-c51320af0ef2.png)

**Comment by masthom** [comment]
It also depends on the query: 
<img width="1759" alt="Bildschirmfoto 2020-07-20 um 16 53 44" src="https://user-images.githubusercontent.com/53256309/87952118-b7ca6580-caa9-11ea-9a42-5f4b6ea4c035.png">
If the order of the two conditions in the query is changed, Pc0 and Pc6 are changing their behaviour: 
<img width="1788" alt="Bildschirmfoto 2020-07-20 um 16 52 25" src="https://user-images.githubusercontent.com/53256309/87952429-1c85c000-caaa-11ea-9f38-f2435dbdb7db.png">

**Comment by masthom** [comment]
If I am doing the query with the same one first knot it looks fine: 
<img width="1764" alt="Bildschirmfoto 2020-07-20 um 17 26 53" src="https://user-images.githubusercontent.com/53256309/87955725-64a6e180-caae-11ea-8ea8-7af5c685d9ac.png">
But changing the order again gives the following result: 
<img width="1764" alt="Bildschirmfoto 2020-07-20 um 17 25 59" src="https://user-images.githubusercontent.com/53256309/87955797-7d16fc00-caae-11ea-9306-c47c7663dc37.png">

**Comment by musicEnfanthen** [comment]
Should be improved now with the latest release: https://github.com/webern-unibas-ch/awg-app/releases/tag/v0.7.18

@masthom Could you have a look and confirm, please?

**Comment by musicEnfanthen** [comment]
Does work now.
