### ISSUE TITLE
[EDITION/GRAPH] Problems using a touchpad

### ISSUE THREAD

**Issue by masthom** [webern-unibas-ch/awg-app#23]
For some reasons it's not possible anymore to grasp and move the nodes in the visualization of the dynamic graph by using a touchpad (and not a mouse). I remember it worked fine earlier this year (spring or summer)?

**Comment by musicEnfanthen** [comment]
It is broken for mouse usage, too. I am investigating.

**Comment by musicEnfanthen** [comment]
Ok, I think I found the problem. After updating the d3 libraries (that are used to create the graph view) to their latest version, they internally use now d3 version 6 which introduced a breaking change regarding event listeners.

Fixed this issue already according to the migration guide: https://observablehq.com/@d3/d3v6-migration-guide#events

Should be available with the next release that I hope to trigger these days. Could you then have a look, please, if the touchpad issue still exists?

**Comment by musicEnfanthen** [comment]
Fixed in  e96becb

**Comment by masthom** [comment]
Awesome!
