### ISSUE TITLE
Deprecated sketch sigla in modal snippets

### ISSUE THREAD

**Issue by musicEnfanthen** [webern-unibas-ch/awg-app#428]
The modal snippets in the [modal component](https://github.com/webern-unibas-ch/awg-app/blob/726c7843fe687e10087b303ac134ac4f973b7576/src/app/shared/modal/modal.component.ts#L22-L25) still use the older system of sketch sigla and should be adjusted.

**Comment by masthom** [comment]
Looks like component "OP12_SHEET_COMING_SOON" is not necessary any more since supplementing M 212 Sk1. Adjusted anyway in PR [#484](https://github.com/webern-unibas-ch/awg-app/pull/484).
